osx_image: xcode8
language: objective-c
script:
- xcodebuild test -project IoniconsKit.xcodeproj -scheme IoniconsKit -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' | xcpretty -c
- pod lib lint
